server.port: 7000
server.error.include-message: always

app:
  movie-service:
    host: localhost
    port: 7001
  comment-service:
    host: localhost
    port: 7002
  rating-service:
    host: localhost
    port: 7003
  screening-service:
    host: localhost
    port: 7004

logging:
  level:
    root: INFO
    se.magnus: DEBUG
