api:

  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Contact
      url: My
      email: me@mail.com

  movie-composite:

    get-composite-movie:
      description: Returns a composite view of the specified movie id
      notes: |
        # Normal response
        If the requested product id is found the method will return information regarding:
        1. Movie information
        1. Ratings
        1. Comments
        1. Screenings
        1. Service Addresses
        (technical information regarding the addresses of the microservices that created the response)

        # Expected partial and error responses
        1. If no movie information is found, a <b>404 - Not Found</b> error will be returned
        1. In no ratings, comments or screenings are found for a movie, a partial response will be returned



server.port: 7000
server.error.include-message: always

app:
  movie-service:
    host: localhost
    port: 7001
  comment-service:
    host: localhost
    port: 7002
  rating-service:
    host: localhost
    port: 7003
  screening-service:
    host: localhost
    port: 7004

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring.profiles: docker

server.port: 8080

app:
  movie-service:
    host: movie
    port: 8080
  rating-service:
    host: rating
    port: 8080
  comment-service:
    host: comment
    port: 8080
  screening-service:
    host: screening
    port: 8080
